// 배지 정의 (30종+) — 게이미피케이션 핵심 콘텐츠
import { Badge } from '@/types/badge';

export const BADGES: Badge[] = [
  // === 할 일 완료 배지 ===
  {
    id: 'first_step',
    name: { ko: '첫 걸음', en: 'First Step' },
    description: { ko: '첫 번째 할 일을 완료하세요', en: 'Complete your first task' },
    icon: '👣',
    rarity: 'common',
    condition: { type: 'task_complete', target: 1 },
    xpReward: 10,
  },
  {
    id: 'task_10',
    name: { ko: '열정 시작', en: 'Getting Started' },
    description: { ko: '할 일 10개를 완료하세요', en: 'Complete 10 tasks' },
    icon: '🌱',
    rarity: 'common',
    condition: { type: 'task_complete', target: 10 },
    xpReward: 30,
  },
  {
    id: 'task_50',
    name: { ko: '꾸준한 실행자', en: 'Steady Doer' },
    description: { ko: '할 일 50개를 완료하세요', en: 'Complete 50 tasks' },
    icon: '⚡',
    rarity: 'rare',
    condition: { type: 'task_complete', target: 50 },
    xpReward: 80,
  },
  {
    id: 'task_100',
    name: { ko: '백전백승', en: 'Centurion' },
    description: { ko: '할 일 100개를 완료하세요', en: 'Complete 100 tasks' },
    icon: '🏅',
    rarity: 'rare',
    condition: { type: 'task_complete', target: 100 },
    xpReward: 150,
  },
  {
    id: 'task_500',
    name: { ko: '할 일의 신', en: 'Task God' },
    description: { ko: '할 일 500개를 완료하세요', en: 'Complete 500 tasks' },
    icon: '👑',
    rarity: 'epic',
    condition: { type: 'task_complete', target: 500 },
    xpReward: 500,
  },
  {
    id: 'task_1000',
    name: { ko: '전설의 완료왕', en: 'Legendary Finisher' },
    description: { ko: '할 일 1000개를 완료하세요', en: 'Complete 1000 tasks' },
    icon: '🌟',
    rarity: 'legendary',
    condition: { type: 'task_complete', target: 1000 },
    xpReward: 1000,
  },

  // === 스트릭 배지 ===
  {
    id: 'streak_3',
    name: { ko: '3일의 불꽃', en: '3-Day Fire' },
    description: { ko: '3일 연속 달성하세요', en: 'Achieve a 3-day streak' },
    icon: '🔥',
    rarity: 'common',
    condition: { type: 'streak', target: 3 },
    xpReward: 15,
  },
  {
    id: 'streak_7',
    name: { ko: '일주일 전사', en: 'Week Warrior' },
    description: { ko: '7일 연속 달성하세요', en: 'Achieve a 7-day streak' },
    icon: '⚔️',
    rarity: 'common',
    condition: { type: 'streak', target: 7 },
    xpReward: 30,
  },
  {
    id: 'streak_30',
    name: { ko: '한 달의 기적', en: 'Monthly Miracle' },
    description: { ko: '30일 연속 달성하세요', en: 'Achieve a 30-day streak' },
    icon: '🌙',
    rarity: 'rare',
    condition: { type: 'streak', target: 30 },
    xpReward: 100,
  },
  {
    id: 'streak_100',
    name: { ko: '100일 전설', en: '100-Day Legend' },
    description: { ko: '100일 연속 달성하세요', en: 'Achieve a 100-day streak' },
    icon: '💎',
    rarity: 'epic',
    condition: { type: 'streak', target: 100 },
    xpReward: 300,
  },
  {
    id: 'streak_365',
    name: { ko: '1년의 왕', en: 'Year King' },
    description: { ko: '365일 연속 달성하세요', en: 'Achieve a 365-day streak' },
    icon: '🏆',
    rarity: 'legendary',
    condition: { type: 'streak', target: 365 },
    xpReward: 2000,
  },

  // === 습관 배지 ===
  {
    id: 'habit_start',
    name: { ko: '습관의 시작', en: 'Habit Starter' },
    description: { ko: '첫 습관 체크를 하세요', en: 'Check your first habit' },
    icon: '🌿',
    rarity: 'common',
    condition: { type: 'habit_check', target: 1 },
    xpReward: 10,
  },
  {
    id: 'habit_50',
    name: { ko: '습관 수집가', en: 'Habit Collector' },
    description: { ko: '습관 50회 체크하세요', en: 'Check habits 50 times' },
    icon: '🎯',
    rarity: 'rare',
    condition: { type: 'habit_check', target: 50 },
    xpReward: 80,
  },
  {
    id: 'habit_200',
    name: { ko: '습관 마스터', en: 'Habit Master' },
    description: { ko: '습관 200회 체크하세요', en: 'Check habits 200 times' },
    icon: '🧙',
    rarity: 'epic',
    condition: { type: 'habit_check', target: 200 },
    xpReward: 300,
  },
  {
    id: 'habit_500',
    name: { ko: '습관의 전설', en: 'Habit Legend' },
    description: { ko: '습관 500회 체크하세요', en: 'Check habits 500 times' },
    icon: '🌈',
    rarity: 'legendary',
    condition: { type: 'habit_check', target: 500 },
    xpReward: 800,
  },

  // === 소셜 배지 ===
  {
    id: 'first_post',
    name: { ko: '첫 공유', en: 'First Share' },
    description: { ko: '첫 포스트를 작성하세요', en: 'Create your first post' },
    icon: '📝',
    rarity: 'common',
    condition: { type: 'social', target: 1 },
    xpReward: 10,
  },
  {
    id: 'social_10',
    name: { ko: '소셜 활동가', en: 'Social Activist' },
    description: { ko: '포스트 10개를 작성하세요', en: 'Create 10 posts' },
    icon: '💬',
    rarity: 'common',
    condition: { type: 'social', target: 10 },
    xpReward: 30,
  },
  {
    id: 'social_star',
    name: { ko: '소셜 스타', en: 'Social Star' },
    description: { ko: '포스트 50개를 작성하세요', en: 'Create 50 posts' },
    icon: '⭐',
    rarity: 'rare',
    condition: { type: 'social', target: 50 },
    xpReward: 100,
  },
  {
    id: 'influencer',
    name: { ko: '인플루언서', en: 'Influencer' },
    description: { ko: '포스트 100개를 작성하세요', en: 'Create 100 posts' },
    icon: '🎤',
    rarity: 'epic',
    condition: { type: 'social', target: 100 },
    xpReward: 300,
  },

  // === 레벨 배지 ===
  {
    id: 'level_5',
    name: { ko: '성장의 새싹', en: 'Growing Sprout' },
    description: { ko: '레벨 5에 도달하세요', en: 'Reach level 5' },
    icon: '🌱',
    rarity: 'common',
    condition: { type: 'level', target: 5 },
    xpReward: 20,
  },
  {
    id: 'level_10',
    name: { ko: '견습 모험가', en: 'Apprentice' },
    description: { ko: '레벨 10에 도달하세요', en: 'Reach level 10' },
    icon: '🗡️',
    rarity: 'rare',
    condition: { type: 'level', target: 10 },
    xpReward: 50,
  },
  {
    id: 'level_25',
    name: { ko: '숙련 전사', en: 'Skilled Warrior' },
    description: { ko: '레벨 25에 도달하세요', en: 'Reach level 25' },
    icon: '🛡️',
    rarity: 'epic',
    condition: { type: 'level', target: 25 },
    xpReward: 200,
  },
  {
    id: 'level_50',
    name: { ko: '마스터', en: 'Master' },
    description: { ko: '레벨 50에 도달하세요', en: 'Reach level 50' },
    icon: '👑',
    rarity: 'legendary',
    condition: { type: 'level', target: 50 },
    xpReward: 1000,
  },

  // === 특별 배지 ===
  {
    id: 'early_bird',
    name: { ko: '얼리버드', en: 'Early Bird' },
    description: { ko: '오전 6시 이전에 할 일을 완료하세요', en: 'Complete a task before 6 AM' },
    icon: '🐦',
    rarity: 'rare',
    condition: { type: 'special', target: 0 },
    xpReward: 50,
  },
  {
    id: 'night_owl',
    name: { ko: '올빼미', en: 'Night Owl' },
    description: { ko: '자정 이후에 할 일을 완료하세요', en: 'Complete a task after midnight' },
    icon: '🦉',
    rarity: 'rare',
    condition: { type: 'special', target: 0 },
    xpReward: 50,
  },
  {
    id: 'perfect_week',
    name: { ko: '완벽한 한 주', en: 'Perfect Week' },
    description: { ko: '일주일간 모든 할 일을 완료하세요', en: 'Complete all tasks for a week' },
    icon: '🌟',
    rarity: 'epic',
    condition: { type: 'special', target: 0 },
    xpReward: 150,
  },
  {
    id: 'multitasker',
    name: { ko: '멀티태스커', en: 'Multitasker' },
    description: { ko: '하루에 10개 이상 할 일을 완료하세요', en: 'Complete 10+ tasks in a day' },
    icon: '🎪',
    rarity: 'rare',
    condition: { type: 'special', target: 0 },
    xpReward: 80,
  },
  {
    id: 'category_master',
    name: { ko: '카테고리 마스터', en: 'Category Master' },
    description: { ko: '한 카테고리에서 100개 할 일을 완료하세요', en: 'Complete 100 tasks in one category' },
    icon: '🎓',
    rarity: 'epic',
    condition: { type: 'special', target: 0 },
    xpReward: 200,
  },
  {
    id: 'weekend_warrior',
    name: { ko: '주말 전사', en: 'Weekend Warrior' },
    description: { ko: '주말에 5개 이상 할 일을 완료하세요', en: 'Complete 5+ tasks on weekend' },
    icon: '🏖️',
    rarity: 'rare',
    condition: { type: 'special', target: 0 },
    xpReward: 60,
  },
  {
    id: 'speed_runner',
    name: { ko: '스피드러너', en: 'Speed Runner' },
    description: { ko: '마감일 3일 전에 할 일을 완료하세요', en: 'Complete a task 3 days before deadline' },
    icon: '⚡',
    rarity: 'rare',
    condition: { type: 'special', target: 0 },
    xpReward: 40,
  },
];
